name: test
on: [push]
jobs:
  test-against-gitlab:
    name: Test against https://gitlab.com/eic/test-trigger-gitlab-ci
    runs-on: ubuntu-latest
    steps:
    - name: Trigger pipeline on test-trigger-gitlab-ci
      id: trigger
      uses: eic/trigger-gitlab-ci@main
      with:
        url: "https://gitlab.com"
        token: ${{ secrets.TOKEN }}
        project_id: 37728736
        variables: |
          VAR1=value1
          VAR2=value2
    - name: Print web_url for further use
      run: |
        echo ${{ steps.trigger.outputs.web_url }}
